"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { NavbarContext } from "./components/navbar/NavbarContext";
import ChildComponent from "./components/child/ChildComponent";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface RootLayoutProps {
  children: React.ReactNode;
}

const BaseLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <ChildComponent>{children}</ChildComponent>
      </body>
    </html>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [navbarHeight, setNavbarHeight] = useState<number>(0);

  return (
    <NavbarContext.Provider value={{ navbarHeight, setNavbarHeight }}>
      <BaseLayout>{children}</BaseLayout>
    </NavbarContext.Provider>
  );
}
