export { default as IconEmail16px } from './16px/IconEmail16px.svg'
export { default as IconLocation16px } from './16px/IconLocation16px.svg'
export { default as GoogleSafeBrowsing } from './GoogleSafeBrowsing.svg'
export { default as LogoViaMidia } from './Logo-ViaMidia.svg'
export { default as PhoneIcon } from './PhoneIcon.svg'
export { default as Studio1001 } from './studio1001.svg'

// Logos
export { default as LogoA2 } from './logos/LogoA2.svg'
export { default as LogoBelgo } from './logos/LogoBelgo.svg'
export { default as LogoCacauShow } from './logos/LogoCacauShow.svg'
export { default as LogoCopacabana } from './logos/LogoCopacabana.svg'
export { default as LogoGiba } from './logos/LogoGiba.svg'
export { default as LogoInService } from './logos/LogoInService.svg'
export { default as LogoNatsumi } from './logos/LogoNatsumi.svg'
export { default as LogoNestle } from './logos/LogoNestle.svg'
export { default as LogoNovaExpress } from './logos/LogoNovaExpress.svg'
export { default as LogoOdontoCompany } from './logos/LogoOdontoCompany.svg'
export { default as LogoResolv } from './logos/LogoResolv.svg'
