export { default as Studio1001 } from './studio1001.svg'
export { default as LogoViaMidia } from './Logo-ViaMidia.svg'
export { default as GoogleSafeBrowsing } from './GoogleSafeBrowsing.svg'
export { default as PhoneIcon } from './PhoneIcon.svg'
export { default as IconEmail16px } from './16px/IconEmail16px.svg'
export { default as IconLocation16px } from './16px/IconLocation16px.svg'